### PR TITLE
fix(meta): Add python-graphviz in dependencies

### PR DESCRIPTION
**Pull request by FernandezMathieu**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by FernandezMathieu** [comment]
Hi @oualib @afard 

Few of our users faced issues with the conda-forge installation of VerticaPy when they were using the plot_tree method, they got this error : ModuleNotFoundError: No module named 'graphviz'.
They tried to install "graphviz" with conda to resolve the problem, but it doesn't work.

We found that conda forge `conda install graphviz" will install the Graphviz software instead of the python librarie.
So, i added "python-graphviz" in the dependencies part of the meta file to fix the issue.

Regards.

**Comment by FernandezMathieu** [comment]
@conda-forge-admin please rerender

**Comment by afard** [comment]
Hi @FernandezMathieu,
Thanks for taking care of this.
Do you know why the checks on the PR have failed?

**Comment by FernandezMathieu** [comment]
> Hi @FernandezMathieu, Thanks for taking care of this. Do you know why the checks on the PR have failed?

@afard  Look like the error is thrown when the pipe try to import VerticaPy during the test phase. You can check the pipeline status and see the error [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=490940&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d)

**Comment by afard** [comment]
I made another PR which has all tests pass.

**Comment by afard** [comment]
I made another PR which has all tests pass.

**Pull request closed without merging**
